from .dashboard import render_dashboard
from .ai_assistant import render_ai_assistant
from .notes import render_notes
from .tasks import render_tasks
from .flashcards import render_flashcards
from .pomodoro import render_pomodoro
from .quiz import render_quiz
from .analytics import render_analytics
from .community import render_community
from .toolkit import render_toolkit
